{
  "formatVersion": "1.1",
  "component": {
    "group": "me.heizi.kotlinx",
    "module": "khell-log",
    "version": "0.0.0-alpha00",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "khell-log-0.0.0-alpha00.jar",
          "url": "khell-log-0.0.0-alpha00.jar",
          "size": 676,
          "sha512": "c4cd39ca8d1f55b6eb913b312bceca87d7076601a7605f992426c1e2aa224a5d348b69df73702d60296b828736937791db4c469761ab10f3b89fa4eb51f7d98c",
          "sha256": "7ab528832cf06f706e980734a0a1040cfedadda6440c2f1077a07d00a8703fae",
          "sha1": "d2adae702059734d47897ac2129d619af01eeeca",
          "md5": "273b75c50330808aef0bfb2213c68fb2"
        }
      ]
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../khell-log-jvm/0.0.0-alpha00/khell-log-jvm-0.0.0-alpha00.module",
        "group": "me.heizi.kotlinx",
        "module": "khell-log-jvm",
        "version": "0.0.0-alpha00"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../khell-log-jvm/0.0.0-alpha00/khell-log-jvm-0.0.0-alpha00.module",
        "group": "me.heizi.kotlinx",
        "module": "khell-log-jvm",
        "version": "0.0.0-alpha00"
      }
    }
  ]
}
