{
  "formatVersion": "1.1",
  "component": {
    "group": "me.heizi.monet-kdrag0n",
    "module": "compose-m3",
    "version": "0.0.1-alpha05",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.5.1"
          }
        }
      ],
      "files": [
        {
          "name": "compose-m3-metadata-0.0.1-alpha05.jar",
          "url": "compose-m3-0.0.1-alpha05.jar",
          "size": 723,
          "sha512": "8cfc10534afea20db3dc39af316566d61310ea8dbe63f5581346ae120d99433cc43ae17f0b62a17a67e2db344e689bfe5b7e2e63d69b44df4c6f99346dbdedd5",
          "sha256": "e65638a713e25d90a8f5d114dd1d1f9e133d995ad70f4dcce1e9cff396a2222b",
          "sha1": "6f2436b2a09c2f45ac898fdd99704dbc09a46035",
          "md5": "51300ae3c271318bdcc298c7582d73c7"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "compose-m3-kotlin-0.0.1-alpha05-sources.jar",
          "url": "compose-m3-0.0.1-alpha05-sources.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    },
    {
      "name": "window-stylerApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm",
        "system.platform": "multiplatform",
        "system.platform.fork": "window-styler"
      },
      "available-at": {
        "url": "../../compose-m3-window-styler/0.0.1-alpha05/compose-m3-window-styler-0.0.1-alpha05.module",
        "group": "me.heizi.monet-kdrag0n",
        "module": "compose-m3-window-styler",
        "version": "0.0.1-alpha05"
      }
    },
    {
      "name": "window-stylerRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm",
        "system.platform": "multiplatform",
        "system.platform.fork": "window-styler"
      },
      "available-at": {
        "url": "../../compose-m3-window-styler/0.0.1-alpha05/compose-m3-window-styler-0.0.1-alpha05.module",
        "group": "me.heizi.monet-kdrag0n",
        "module": "compose-m3-window-styler",
        "version": "0.0.1-alpha05"
      }
    },
    {
      "name": "window-stylerSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm",
        "system.platform": "multiplatform",
        "system.platform.fork": "window-styler"
      },
      "available-at": {
        "url": "../../compose-m3-window-styler/0.0.1-alpha05/compose-m3-window-styler-0.0.1-alpha05.module",
        "group": "me.heizi.monet-kdrag0n",
        "module": "compose-m3-window-styler",
        "version": "0.0.1-alpha05"
      }
    },
    {
      "name": "windowsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm",
        "system.platform": "windows",
        "system.platform.fork": "main"
      },
      "available-at": {
        "url": "../../compose-m3-windows/0.0.1-alpha05/compose-m3-windows-0.0.1-alpha05.module",
        "group": "me.heizi.monet-kdrag0n",
        "module": "compose-m3-windows",
        "version": "0.0.1-alpha05"
      }
    },
    {
      "name": "windowsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm",
        "system.platform": "windows",
        "system.platform.fork": "main"
      },
      "available-at": {
        "url": "../../compose-m3-windows/0.0.1-alpha05/compose-m3-windows-0.0.1-alpha05.module",
        "group": "me.heizi.monet-kdrag0n",
        "module": "compose-m3-windows",
        "version": "0.0.1-alpha05"
      }
    },
    {
      "name": "windowsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm",
        "system.platform": "windows",
        "system.platform.fork": "main"
      },
      "available-at": {
        "url": "../../compose-m3-windows/0.0.1-alpha05/compose-m3-windows-0.0.1-alpha05.module",
        "group": "me.heizi.monet-kdrag0n",
        "module": "compose-m3-windows",
        "version": "0.0.1-alpha05"
      }
    },
    {
      "name": "windows-jnaApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm",
        "system.platform": "windows",
        "system.platform.fork": "jna"
      },
      "available-at": {
        "url": "../../compose-m3-windows-jna/0.0.1-alpha05/compose-m3-windows-jna-0.0.1-alpha05.module",
        "group": "me.heizi.monet-kdrag0n",
        "module": "compose-m3-windows-jna",
        "version": "0.0.1-alpha05"
      }
    },
    {
      "name": "windows-jnaRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm",
        "system.platform": "windows",
        "system.platform.fork": "jna"
      },
      "available-at": {
        "url": "../../compose-m3-windows-jna/0.0.1-alpha05/compose-m3-windows-jna-0.0.1-alpha05.module",
        "group": "me.heizi.monet-kdrag0n",
        "module": "compose-m3-windows-jna",
        "version": "0.0.1-alpha05"
      }
    },
    {
      "name": "windows-jnaSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm",
        "system.platform": "windows",
        "system.platform.fork": "jna"
      },
      "available-at": {
        "url": "../../compose-m3-windows-jna/0.0.1-alpha05/compose-m3-windows-jna-0.0.1-alpha05.module",
        "group": "me.heizi.monet-kdrag0n",
        "module": "compose-m3-windows-jna",
        "version": "0.0.1-alpha05"
      }
    }
  ]
}
