{
  "formatVersion": "1.1",
  "component": {
    "group": "me.heizi.apk.parser",
    "module": "compose-desktop-ext",
    "version": "0.0.1-alpha04",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.desktop",
          "module": "desktop-jvm-windows-x64",
          "version": {
            "requires": "1.3.0-beta03"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "compose-desktop-ext-0.0.1-alpha04.jar",
          "url": "compose-desktop-ext-0.0.1-alpha04.jar",
          "size": 12313,
          "sha512": "e0fe035f5d2e27a663d932f449c11497b5c000ee03c8cfd30f11d546df55ba0e6090a448fe2d3bcb78cc9a058313424c08dbb6518cfed9bdf2284f88c5c84468",
          "sha256": "267510dc63fe3152b6239f3c1c96d47e23d0a538fe2077f5ba95e2d18d0205bb",
          "sha1": "9a07e7baae335283aaa621235fc7b84aa7c60867",
          "md5": "f7b3bea308f534fc887fb24916af50ad"
        }
      ]
    },
    {
      "name": "runtimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.dongliu.apk.parser",
          "module": "apk-parser",
          "version": {
            "requires": "0.0.1-alpha04"
          }
        },
        {
          "group": "org.jetbrains.compose.desktop",
          "module": "desktop-jvm-windows-x64",
          "version": {
            "requires": "1.3.0-beta03"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "compose-desktop-ext-0.0.1-alpha04.jar",
          "url": "compose-desktop-ext-0.0.1-alpha04.jar",
          "size": 12313,
          "sha512": "e0fe035f5d2e27a663d932f449c11497b5c000ee03c8cfd30f11d546df55ba0e6090a448fe2d3bcb78cc9a058313424c08dbb6518cfed9bdf2284f88c5c84468",
          "sha256": "267510dc63fe3152b6239f3c1c96d47e23d0a538fe2077f5ba95e2d18d0205bb",
          "sha1": "9a07e7baae335283aaa621235fc7b84aa7c60867",
          "md5": "f7b3bea308f534fc887fb24916af50ad"
        }
      ]
    }
  ]
}
