{
  "formatVersion": "1.1",
  "component": {
    "group": "me.heizi.kotlinx",
    "module": "khell",
    "version": "0.0.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "me.heizi.kotlinx",
          "module": "khell-log",
          "version": {
            "requires": "0.0.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "khell-0.0.0-alpha01.jar",
          "url": "khell-0.0.0-alpha01.jar",
          "size": 707,
          "sha512": "3ae62cc8ad68ddf3a6c65db7129e4138014eba5e72dc2dbc198576e6507d4ab06610aa42bf275769345bb7bee21e9b475d9b8f65dfa3afa11277e8773093fd55",
          "sha256": "be552d06520e6562055dc285725b561a98a33178de0bfe40d93f67e13c0a1fbb",
          "sha1": "ca24016792b8b49911b2771b9b932be534883c8e",
          "md5": "08418e4801247a50dcb3dc62d31daea3"
        }
      ]
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../khell-jvm/0.0.0-alpha01/khell-jvm-0.0.0-alpha01.module",
        "group": "me.heizi.kotlinx",
        "module": "khell-jvm",
        "version": "0.0.0-alpha01"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../khell-jvm/0.0.0-alpha01/khell-jvm-0.0.0-alpha01.module",
        "group": "me.heizi.kotlinx",
        "module": "khell-jvm",
        "version": "0.0.0-alpha01"
      }
    }
  ]
}
