{
  "formatVersion": "1.1",
  "component": {
    "group": "me.heizi.apk.parser",
    "module": "compose-desktop-ext",
    "version": "0.0.1-alpha02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.desktop",
          "module": "desktop-jvm-windows-x64",
          "version": {
            "requires": "1.3.0-beta03"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "compose-desktop-ext-0.0.1-alpha02.jar",
          "url": "compose-desktop-ext-0.0.1-alpha02.jar",
          "size": 12318,
          "sha512": "4fe6b5a0b5e5220eeb36b58b435a734462752f31cf8ab142008236fe4983b8723d9fc805ade46950b639ca12997692db244556ece662e304ba3ab6e7dc1bfd44",
          "sha256": "97ecbc3652b61a4281e09d20dee22bf34aeb973615b57d850e857748c038ad0d",
          "sha1": "59b1244f013dc4a64b8e47111c713f1cd57a024c",
          "md5": "cd168b1ad2b571726757c93d782d85a8"
        }
      ]
    },
    {
      "name": "runtimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.dongliu.apk.parser",
          "module": "apk-parser",
          "version": {
            "requires": "0.0.1-alpha02"
          }
        },
        {
          "group": "org.jetbrains.compose.desktop",
          "module": "desktop-jvm-windows-x64",
          "version": {
            "requires": "1.3.0-beta03"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "compose-desktop-ext-0.0.1-alpha02.jar",
          "url": "compose-desktop-ext-0.0.1-alpha02.jar",
          "size": 12318,
          "sha512": "4fe6b5a0b5e5220eeb36b58b435a734462752f31cf8ab142008236fe4983b8723d9fc805ade46950b639ca12997692db244556ece662e304ba3ab6e7dc1bfd44",
          "sha256": "97ecbc3652b61a4281e09d20dee22bf34aeb973615b57d850e857748c038ad0d",
          "sha1": "59b1244f013dc4a64b8e47111c713f1cd57a024c",
          "md5": "cd168b1ad2b571726757c93d782d85a8"
        }
      ]
    }
  ]
}
