{
  "formatVersion": "1.1",
  "component": {
    "group": "me.heizi.monet-kdrag0n",
    "module": "compose-m3",
    "version": "0.0.1-alpha03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "compose-m3-metadata-0.0.1-alpha03.jar",
          "url": "compose-m3-0.0.1-alpha03.jar",
          "size": 740,
          "sha512": "a6115c399ebf7951f05294c0e2d58d7037e4888faead4f67f178cd56a5eaa2915982618a13cdd374f6eb64fb2b79e57c95de3c0b1f2fb4c3ed461e569cb12895",
          "sha256": "25b4853d8ac00ed8b76d1f94e332154153f5864c5a454cb16ddeb0d246ddce49",
          "sha1": "00b5652835c620efe37590ae94b198dd78dc0473",
          "md5": "c57e2a449394f4b22da5e6284b2de3dd"
        }
      ]
    },
    {
      "name": "window-stylerApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm",
        "system.platform": "multiplatform",
        "system.platform.fork": "window-styler"
      },
      "available-at": {
        "url": "../../compose-m3-window-styler/0.0.1-alpha03/compose-m3-window-styler-0.0.1-alpha03.module",
        "group": "me.heizi.monet-kdrag0n",
        "module": "compose-m3-window-styler",
        "version": "0.0.1-alpha03"
      }
    },
    {
      "name": "window-stylerRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm",
        "system.platform": "multiplatform",
        "system.platform.fork": "window-styler"
      },
      "available-at": {
        "url": "../../compose-m3-window-styler/0.0.1-alpha03/compose-m3-window-styler-0.0.1-alpha03.module",
        "group": "me.heizi.monet-kdrag0n",
        "module": "compose-m3-window-styler",
        "version": "0.0.1-alpha03"
      }
    },
    {
      "name": "windowsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm",
        "system.platform": "windows",
        "system.platform.fork": "main"
      },
      "available-at": {
        "url": "../../compose-m3-windows/0.0.1-alpha03/compose-m3-windows-0.0.1-alpha03.module",
        "group": "me.heizi.monet-kdrag0n",
        "module": "compose-m3-windows",
        "version": "0.0.1-alpha03"
      }
    },
    {
      "name": "windowsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm",
        "system.platform": "windows",
        "system.platform.fork": "main"
      },
      "available-at": {
        "url": "../../compose-m3-windows/0.0.1-alpha03/compose-m3-windows-0.0.1-alpha03.module",
        "group": "me.heizi.monet-kdrag0n",
        "module": "compose-m3-windows",
        "version": "0.0.1-alpha03"
      }
    },
    {
      "name": "windows-jnaApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm",
        "system.platform": "windows",
        "system.platform.fork": "jna"
      },
      "available-at": {
        "url": "../../compose-m3-windows-jna/0.0.1-alpha03/compose-m3-windows-jna-0.0.1-alpha03.module",
        "group": "me.heizi.monet-kdrag0n",
        "module": "compose-m3-windows-jna",
        "version": "0.0.1-alpha03"
      }
    },
    {
      "name": "windows-jnaRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm",
        "system.platform": "windows",
        "system.platform.fork": "jna"
      },
      "available-at": {
        "url": "../../compose-m3-windows-jna/0.0.1-alpha03/compose-m3-windows-jna-0.0.1-alpha03.module",
        "group": "me.heizi.monet-kdrag0n",
        "module": "compose-m3-windows-jna",
        "version": "0.0.1-alpha03"
      }
    }
  ]
}
