{
  "formatVersion": "1.1",
  "component": {
    "group": "me.heizi.apk.parser",
    "module": "compose-desktop-ext",
    "version": "0.0.1-alpha03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.desktop",
          "module": "desktop-jvm-windows-x64",
          "version": {
            "requires": "1.3.0-beta03"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "compose-desktop-ext-0.0.1-alpha03.jar",
          "url": "compose-desktop-ext-0.0.1-alpha03.jar",
          "size": 12314,
          "sha512": "5fe06d2ce7b07206148bd6748a98a644890015ab60d6d47093b15e9a8a2928bb46a82ce3868ffc99d8f9966522149356dfb65dbd1e85d26dd6c4a42827a8166f",
          "sha256": "fad7d8c597d1f5fb87ae93453a3347e885bef80d3a2ab612d07483e1907a6407",
          "sha1": "b3471b6990e844afe03cbbccf660a322cc7ca8d1",
          "md5": "199dc35d0c3a86684b2e651b4488cabd"
        }
      ]
    },
    {
      "name": "runtimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.dongliu.apk.parser",
          "module": "apk-parser",
          "version": {
            "requires": "0.0.1-alpha03"
          }
        },
        {
          "group": "org.jetbrains.compose.desktop",
          "module": "desktop-jvm-windows-x64",
          "version": {
            "requires": "1.3.0-beta03"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "compose-desktop-ext-0.0.1-alpha03.jar",
          "url": "compose-desktop-ext-0.0.1-alpha03.jar",
          "size": 12314,
          "sha512": "5fe06d2ce7b07206148bd6748a98a644890015ab60d6d47093b15e9a8a2928bb46a82ce3868ffc99d8f9966522149356dfb65dbd1e85d26dd6c4a42827a8166f",
          "sha256": "fad7d8c597d1f5fb87ae93453a3347e885bef80d3a2ab612d07483e1907a6407",
          "sha1": "b3471b6990e844afe03cbbccf660a322cc7ca8d1",
          "md5": "199dc35d0c3a86684b2e651b4488cabd"
        }
      ]
    }
  ]
}
