{
  "formatVersion": "1.1",
  "component": {
    "url": "../../compose-m3/0.0.1-alpha02/compose-m3-0.0.1-alpha02.module",
    "group": "me.heizi.monet-kdrag0n",
    "module": "compose-m3",
    "version": "0.0.1-alpha02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "window-stylerApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm",
        "system.platform": "multiplatform",
        "system.platform.fork": "window-styler"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.mayakapps.compose",
          "module": "window-styler",
          "version": {
            "requires": "0.3.2"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna-platform",
          "version": {
            "requires": "5.13.0"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna",
          "version": {
            "requires": "5.13.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "compose-m3-window-styler-0.0.1-alpha02.jar",
          "url": "compose-m3-window-styler-0.0.1-alpha02.jar",
          "size": 28616,
          "sha512": "0201302dc54a927e467fdaefad35864f1540db24000907246c17b3f2a4109b85bc1d7949f6dcbcdda12efef308f22636eade2f814d276ae0823429923fd811e3",
          "sha256": "e74da85b99dffcc3336733386e1fcb61994d888d746c16375567a41e66c6b138",
          "sha1": "c0097fe140efdf5065c857efebf8ab976cb18c88",
          "md5": "30969b0832c956173edc9427e3f1e7c0"
        }
      ]
    },
    {
      "name": "window-stylerRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm",
        "system.platform": "multiplatform",
        "system.platform.fork": "window-styler"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.mayakapps.compose",
          "module": "window-styler",
          "version": {
            "requires": "0.3.2"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna-platform",
          "version": {
            "requires": "5.13.0"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna",
          "version": {
            "requires": "5.13.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "dev.kdrag0n",
          "module": "colorkt",
          "version": {
            "requires": "1.0.5"
          }
        },
        {
          "group": "me.heizi.monet-kdrag0n",
          "module": "monet-kdrag0n",
          "version": {
            "requires": "0.0.1-alpha02"
          }
        }
      ],
      "files": [
        {
          "name": "compose-m3-window-styler-0.0.1-alpha02.jar",
          "url": "compose-m3-window-styler-0.0.1-alpha02.jar",
          "size": 28616,
          "sha512": "0201302dc54a927e467fdaefad35864f1540db24000907246c17b3f2a4109b85bc1d7949f6dcbcdda12efef308f22636eade2f814d276ae0823429923fd811e3",
          "sha256": "e74da85b99dffcc3336733386e1fcb61994d888d746c16375567a41e66c6b138",
          "sha1": "c0097fe140efdf5065c857efebf8ab976cb18c88",
          "md5": "30969b0832c956173edc9427e3f1e7c0"
        }
      ]
    }
  ]
}
