{
  "formatVersion": "1.1",
  "component": {
    "url": "../../compose-m3/0.0.1-alpha02/compose-m3-0.0.1-alpha02.module",
    "group": "me.heizi.monet-kdrag0n",
    "module": "compose-m3",
    "version": "0.0.1-alpha02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "windowsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm",
        "system.platform": "windows",
        "system.platform.fork": "main"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "compose-m3-windows-0.0.1-alpha02.jar",
          "url": "compose-m3-windows-0.0.1-alpha02.jar",
          "size": 18251,
          "sha512": "4682cb3277f811e8a60ae0fb3046b6e50c77ce5f0f6fc6aa275100f98817eba656c2eec4d9216b6f9eb0881b046fb62b8b7c60fe0a3afe4b679ca0bc9189cd82",
          "sha256": "616e2b6178806b9ee79be74cd7d8aff4922653f4c2c37d5ed2db63f2dcccee7d",
          "sha1": "5182b059c764ca31f7578dd620ddeaf28676db95",
          "md5": "96e064de0b775e0dbe81601b8e084229"
        }
      ]
    },
    {
      "name": "windowsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm",
        "system.platform": "windows",
        "system.platform.fork": "main"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "dev.kdrag0n",
          "module": "colorkt",
          "version": {
            "requires": "1.0.5"
          }
        },
        {
          "group": "me.heizi.monet-kdrag0n",
          "module": "monet-kdrag0n",
          "version": {
            "requires": "0.0.1-alpha02"
          }
        }
      ],
      "files": [
        {
          "name": "compose-m3-windows-0.0.1-alpha02.jar",
          "url": "compose-m3-windows-0.0.1-alpha02.jar",
          "size": 18251,
          "sha512": "4682cb3277f811e8a60ae0fb3046b6e50c77ce5f0f6fc6aa275100f98817eba656c2eec4d9216b6f9eb0881b046fb62b8b7c60fe0a3afe4b679ca0bc9189cd82",
          "sha256": "616e2b6178806b9ee79be74cd7d8aff4922653f4c2c37d5ed2db63f2dcccee7d",
          "sha1": "5182b059c764ca31f7578dd620ddeaf28676db95",
          "md5": "96e064de0b775e0dbe81601b8e084229"
        }
      ]
    }
  ]
}
