{
  "formatVersion": "1.1",
  "component": {
    "group": "me.heizi.kotlinx",
    "module": "khell-api",
    "version": "0.0.1-alpha03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "me.heizi.kotlinx",
          "module": "khell-log",
          "version": {
            "requires": "0.0.1-alpha03"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "khell-api-metadata-0.0.1-alpha03.jar",
          "url": "khell-api-0.0.1-alpha03.jar",
          "size": 729,
          "sha512": "0dcf3d41630c5b2716c1664221346cfb6949be987954ca58673b1c4eca381227a374771c6d77eb0059290aa4d5846ec8ce2cd552439b10ea8c18f130f8f6e157",
          "sha256": "4489e112087aa3a4a5c1d07387acd5a24c36eccb452adc2aad19d7ff6ac0abde",
          "sha1": "92a4f6a7d09f7465481e6c9f040279bac7bdcf35",
          "md5": "18cdde17bf7fe581604f9f1ad02e9671"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "khell-api-kotlin-0.0.1-alpha03-sources.jar",
          "url": "khell-api-0.0.1-alpha03-sources.jar",
          "size": 5989,
          "sha512": "a9419633ddc2aed2acf4d67e59f3a289fb842a88a7a9b13e606f17786c4631caa357d998e7510a9156dea04d42c68efa428392756b2414d77bf0a81d311a9d97",
          "sha256": "b47ccc5fe886e869d37d6061c795a3074d626bc5748670dd28f8fc3eb7f3e3b9",
          "sha1": "62ced68de07f117affd38a69dd0870a008aa84a6",
          "md5": "196f5f3beff1d7159bf9c3b828407cd3"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../khell-api-android/0.0.1-alpha03/khell-api-android-0.0.1-alpha03.module",
        "group": "me.heizi.kotlinx",
        "module": "khell-api-android",
        "version": "0.0.1-alpha03"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../khell-api-android/0.0.1-alpha03/khell-api-android-0.0.1-alpha03.module",
        "group": "me.heizi.kotlinx",
        "module": "khell-api-android",
        "version": "0.0.1-alpha03"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../khell-api-android/0.0.1-alpha03/khell-api-android-0.0.1-alpha03.module",
        "group": "me.heizi.kotlinx",
        "module": "khell-api-android",
        "version": "0.0.1-alpha03"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../khell-api-jvm/0.0.1-alpha03/khell-api-jvm-0.0.1-alpha03.module",
        "group": "me.heizi.kotlinx",
        "module": "khell-api-jvm",
        "version": "0.0.1-alpha03"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../khell-api-jvm/0.0.1-alpha03/khell-api-jvm-0.0.1-alpha03.module",
        "group": "me.heizi.kotlinx",
        "module": "khell-api-jvm",
        "version": "0.0.1-alpha03"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../khell-api-jvm/0.0.1-alpha03/khell-api-jvm-0.0.1-alpha03.module",
        "group": "me.heizi.kotlinx",
        "module": "khell-api-jvm",
        "version": "0.0.1-alpha03"
      }
    }
  ]
}
