{
  "formatVersion": "1.1",
  "component": {
    "url": "../../monet-kdrag0n/0.0.1-alpha02/monet-kdrag0n-0.0.1-alpha02.module",
    "group": "me.heizi.monet-kdrag0n",
    "module": "monet-kdrag0n",
    "version": "0.0.1-alpha02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "monet-kdrag0n-jvm-0.0.1-alpha02.jar",
          "url": "monet-kdrag0n-jvm-0.0.1-alpha02.jar",
          "size": 54576,
          "sha512": "dd47d90bf80d4cbbe93911c205d36488d84f7cc3a6b862efdb6fd3823560649e16f9a76969e4fd3b2b1d040ac24bed0fad00fb9b4f66aecfb75f7f03af3bf2fe",
          "sha256": "d08ddd01ef8bb854f1b7053faa2fee07336dc047a989b5e17f5ffadaf5a21ce7",
          "sha1": "d6538dde1d7725306f06b050cf8d5f514654d747",
          "md5": "f4ff60f5c54add72f6ff2c5c9719fa60"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "dev.kdrag0n",
          "module": "colorkt",
          "version": {
            "requires": "1.0.5"
          }
        },
        {
          "group": "io.github.aakira",
          "module": "napier",
          "version": {
            "requires": "2.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "monet-kdrag0n-jvm-0.0.1-alpha02.jar",
          "url": "monet-kdrag0n-jvm-0.0.1-alpha02.jar",
          "size": 54576,
          "sha512": "dd47d90bf80d4cbbe93911c205d36488d84f7cc3a6b862efdb6fd3823560649e16f9a76969e4fd3b2b1d040ac24bed0fad00fb9b4f66aecfb75f7f03af3bf2fe",
          "sha256": "d08ddd01ef8bb854f1b7053faa2fee07336dc047a989b5e17f5ffadaf5a21ce7",
          "sha1": "d6538dde1d7725306f06b050cf8d5f514654d747",
          "md5": "f4ff60f5c54add72f6ff2c5c9719fa60"
        }
      ]
    }
  ]
}
