{
  "formatVersion": "1.1",
  "component": {
    "url": "../../khell/0.0.1-alpha03/khell-0.0.1-alpha03.module",
    "group": "me.heizi.kotlinx",
    "module": "khell",
    "version": "0.0.1-alpha03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        },
        {
          "group": "me.heizi.kotlinx",
          "module": "khell-log",
          "version": {
            "requires": "0.0.1-alpha03"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "khell-release.aar",
          "url": "khell-android-0.0.1-alpha03.aar",
          "size": 86938,
          "sha512": "c7c713ea2c779d354946f8e0cc2ea156cfe224d5bb065559d9f69a902e09bb40a5b3a1da54802d0fa08f088a5a9f2178f6de8e4ed1a89cc8534c962095c5c305",
          "sha256": "3f5520d75065eceae83eab32fd118379bc212f7120b472b507bc2d91bbed47ba",
          "sha1": "8422e657d84a95bec652738d9385cde7194e9003",
          "md5": "adc977daa25b33b846410298d4410436"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "me.heizi.kotlinx",
          "module": "khell-log",
          "version": {
            "requires": "0.0.1-alpha03"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.20"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "me.heizi.kotlinx",
          "module": "khell-api",
          "version": {
            "requires": "0.0.1-alpha03"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "khell-release.aar",
          "url": "khell-android-0.0.1-alpha03.aar",
          "size": 86938,
          "sha512": "c7c713ea2c779d354946f8e0cc2ea156cfe224d5bb065559d9f69a902e09bb40a5b3a1da54802d0fa08f088a5a9f2178f6de8e4ed1a89cc8534c962095c5c305",
          "sha256": "3f5520d75065eceae83eab32fd118379bc212f7120b472b507bc2d91bbed47ba",
          "sha1": "8422e657d84a95bec652738d9385cde7194e9003",
          "md5": "adc977daa25b33b846410298d4410436"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "khell-android-0.0.1-alpha03-sources.jar",
          "url": "khell-android-0.0.1-alpha03-sources.jar",
          "size": 6710,
          "sha512": "81793e04f3f63e7c41aa571f6c2a5bcccb3b309e75c515633a77085f1682e4a8cdf56d5d60568068616f003bbbb0cda69041d6275112c9a33eb25f56ba2899c1",
          "sha256": "f139d9af1b0becc669b11581b14be24fd29aadcecd16945d16305bf58db8f181",
          "sha1": "976ec4ea80a462c597b356cd4cbc28eaada509c9",
          "md5": "60cc35eaf61ecfee21be563d772e1354"
        }
      ]
    }
  ]
}
