{
  "formatVersion": "1.1",
  "component": {
    "url": "../../compose-m3/0.0.1-alpha03/compose-m3-0.0.1-alpha03.module",
    "group": "me.heizi.monet-kdrag0n",
    "module": "compose-m3",
    "version": "0.0.1-alpha03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "windowsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm",
        "system.platform": "windows",
        "system.platform.fork": "main"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "compose-m3-windows-0.0.1-alpha03.jar",
          "url": "compose-m3-windows-0.0.1-alpha03.jar",
          "size": 23019,
          "sha512": "29e055153235dde1319d35937cd43e27793721ca582cc725f4cb2ce446233a2d6038beece2fac3e9e74ff5fe63e5c6eb59b63d3984ec2ce1fb5d272f45f72de6",
          "sha256": "d81073a916cb678b5e6e22b450c12d1455ae7a57e3c87189a21cec8c06db6f29",
          "sha1": "412e6a147bb509fd8a0c63d874743366bdbc4855",
          "md5": "608e2ef239a280b0ecbc79b84ec3a73c"
        }
      ]
    },
    {
      "name": "windowsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm",
        "system.platform": "windows",
        "system.platform.fork": "main"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "dev.kdrag0n",
          "module": "colorkt",
          "version": {
            "requires": "1.0.5"
          }
        },
        {
          "group": "me.heizi.monet-kdrag0n",
          "module": "monet-kdrag0n",
          "version": {
            "requires": "0.0.1-alpha03"
          }
        }
      ],
      "files": [
        {
          "name": "compose-m3-windows-0.0.1-alpha03.jar",
          "url": "compose-m3-windows-0.0.1-alpha03.jar",
          "size": 23019,
          "sha512": "29e055153235dde1319d35937cd43e27793721ca582cc725f4cb2ce446233a2d6038beece2fac3e9e74ff5fe63e5c6eb59b63d3984ec2ce1fb5d272f45f72de6",
          "sha256": "d81073a916cb678b5e6e22b450c12d1455ae7a57e3c87189a21cec8c06db6f29",
          "sha1": "412e6a147bb509fd8a0c63d874743366bdbc4855",
          "md5": "608e2ef239a280b0ecbc79b84ec3a73c"
        }
      ]
    }
  ]
}
