{
  "formatVersion": "1.1",
  "component": {
    "url": "../../compose-m3/0.0.1-alpha03/compose-m3-0.0.1-alpha03.module",
    "group": "me.heizi.monet-kdrag0n",
    "module": "compose-m3",
    "version": "0.0.1-alpha03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "window-stylerApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm",
        "system.platform": "multiplatform",
        "system.platform.fork": "window-styler"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.mayakapps.compose",
          "module": "window-styler",
          "version": {
            "requires": "0.3.2"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna-platform",
          "version": {
            "requires": "5.13.0"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna",
          "version": {
            "requires": "5.13.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "compose-m3-window-styler-0.0.1-alpha03.jar",
          "url": "compose-m3-window-styler-0.0.1-alpha03.jar",
          "size": 34090,
          "sha512": "7e570642dc9463025e4c6f502591f92bb5f00c247b307e00f0b577239aa58fd6005e4f9bbdd895b9990b127e051e6bdf37053dcaecfb4fd4f67864104462918c",
          "sha256": "f9a544941a927f9d995fe847ca1320348bf0212ecbad4348bd455c6fb0233d23",
          "sha1": "ea74a91e0772195ebf7042002908b428d8cbeb6a",
          "md5": "d25e6613d5bd728b739454eab637475c"
        }
      ]
    },
    {
      "name": "window-stylerRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm",
        "system.platform": "multiplatform",
        "system.platform.fork": "window-styler"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.mayakapps.compose",
          "module": "window-styler",
          "version": {
            "requires": "0.3.2"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna-platform",
          "version": {
            "requires": "5.13.0"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna",
          "version": {
            "requires": "5.13.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "dev.kdrag0n",
          "module": "colorkt",
          "version": {
            "requires": "1.0.5"
          }
        },
        {
          "group": "me.heizi.monet-kdrag0n",
          "module": "monet-kdrag0n",
          "version": {
            "requires": "0.0.1-alpha03"
          }
        }
      ],
      "files": [
        {
          "name": "compose-m3-window-styler-0.0.1-alpha03.jar",
          "url": "compose-m3-window-styler-0.0.1-alpha03.jar",
          "size": 34090,
          "sha512": "7e570642dc9463025e4c6f502591f92bb5f00c247b307e00f0b577239aa58fd6005e4f9bbdd895b9990b127e051e6bdf37053dcaecfb4fd4f67864104462918c",
          "sha256": "f9a544941a927f9d995fe847ca1320348bf0212ecbad4348bd455c6fb0233d23",
          "sha1": "ea74a91e0772195ebf7042002908b428d8cbeb6a",
          "md5": "d25e6613d5bd728b739454eab637475c"
        }
      ]
    }
  ]
}
