{
  "formatVersion": "1.1",
  "component": {
    "url": "../../compose-m3/0.0.1-alpha02/compose-m3-0.0.1-alpha02.module",
    "group": "me.heizi.monet-kdrag0n",
    "module": "compose-m3",
    "version": "0.0.1-alpha02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "windows-jnaApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm",
        "system.platform": "windows",
        "system.platform.fork": "jna"
      },
      "dependencies": [
        {
          "group": "net.java.dev.jna",
          "module": "jna-platform",
          "version": {
            "requires": "5.13.0"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna",
          "version": {
            "requires": "5.13.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "compose-m3-windows-jna-0.0.1-alpha02.jar",
          "url": "compose-m3-windows-jna-0.0.1-alpha02.jar",
          "size": 14348,
          "sha512": "698565a84a84459fa9fa1fcc88f1350646c690cc1316da08c7b7dbdd2464bbc496f84f72a7339a9ec5e981387210dad231c75c851a19517f8c16cd108349178f",
          "sha256": "d7af408718d7d11ec179c080f8cb80a90f3d0e33e491739d7277c7a841a3c26a",
          "sha1": "eb225ac097a781a5acacce3f9ea9e84f208a846f",
          "md5": "0b3f90282d787a0b59777d089e20d0ba"
        }
      ]
    },
    {
      "name": "windows-jnaRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm",
        "system.platform": "windows",
        "system.platform.fork": "jna"
      },
      "dependencies": [
        {
          "group": "net.java.dev.jna",
          "module": "jna-platform",
          "version": {
            "requires": "5.13.0"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna",
          "version": {
            "requires": "5.13.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "dev.kdrag0n",
          "module": "colorkt",
          "version": {
            "requires": "1.0.5"
          }
        },
        {
          "group": "me.heizi.monet-kdrag0n",
          "module": "monet-kdrag0n",
          "version": {
            "requires": "0.0.1-alpha02"
          }
        }
      ],
      "files": [
        {
          "name": "compose-m3-windows-jna-0.0.1-alpha02.jar",
          "url": "compose-m3-windows-jna-0.0.1-alpha02.jar",
          "size": 14348,
          "sha512": "698565a84a84459fa9fa1fcc88f1350646c690cc1316da08c7b7dbdd2464bbc496f84f72a7339a9ec5e981387210dad231c75c851a19517f8c16cd108349178f",
          "sha256": "d7af408718d7d11ec179c080f8cb80a90f3d0e33e491739d7277c7a841a3c26a",
          "sha1": "eb225ac097a781a5acacce3f9ea9e84f208a846f",
          "md5": "0b3f90282d787a0b59777d089e20d0ba"
        }
      ]
    }
  ]
}
