{
  "formatVersion": "1.1",
  "component": {
    "url": "../../compose-m3/0.0.1-alpha03/compose-m3-0.0.1-alpha03.module",
    "group": "me.heizi.monet-kdrag0n",
    "module": "compose-m3",
    "version": "0.0.1-alpha03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "windows-jnaApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm",
        "system.platform": "windows",
        "system.platform.fork": "jna"
      },
      "dependencies": [
        {
          "group": "net.java.dev.jna",
          "module": "jna-platform",
          "version": {
            "requires": "5.13.0"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna",
          "version": {
            "requires": "5.13.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "compose-m3-windows-jna-0.0.1-alpha03.jar",
          "url": "compose-m3-windows-jna-0.0.1-alpha03.jar",
          "size": 21192,
          "sha512": "448d9d0aaa82549f74f9c04315abf559cbebe59b00cc818a37cf548371d62f9296b8c1da076d35f31ac4da4324bc68516dbcc7687e7e8520cf6511dc440434c8",
          "sha256": "49b75d0fbfc37801bae5e8fd48be46cfcbc1499bacbfa9989890ee123c356c58",
          "sha1": "87c09a1fed605e4854ae70f3ccc1527eae5335f8",
          "md5": "eea35a3963ad07e58227f150c6a66eb3"
        }
      ]
    },
    {
      "name": "windows-jnaRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm",
        "system.platform": "windows",
        "system.platform.fork": "jna"
      },
      "dependencies": [
        {
          "group": "net.java.dev.jna",
          "module": "jna-platform",
          "version": {
            "requires": "5.13.0"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna",
          "version": {
            "requires": "5.13.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "dev.kdrag0n",
          "module": "colorkt",
          "version": {
            "requires": "1.0.5"
          }
        },
        {
          "group": "me.heizi.monet-kdrag0n",
          "module": "monet-kdrag0n",
          "version": {
            "requires": "0.0.1-alpha03"
          }
        }
      ],
      "files": [
        {
          "name": "compose-m3-windows-jna-0.0.1-alpha03.jar",
          "url": "compose-m3-windows-jna-0.0.1-alpha03.jar",
          "size": 21192,
          "sha512": "448d9d0aaa82549f74f9c04315abf559cbebe59b00cc818a37cf548371d62f9296b8c1da076d35f31ac4da4324bc68516dbcc7687e7e8520cf6511dc440434c8",
          "sha256": "49b75d0fbfc37801bae5e8fd48be46cfcbc1499bacbfa9989890ee123c356c58",
          "sha1": "87c09a1fed605e4854ae70f3ccc1527eae5335f8",
          "md5": "eea35a3963ad07e58227f150c6a66eb3"
        }
      ]
    }
  ]
}
