{
  "formatVersion": "1.1",
  "component": {
    "url": "../../monet-kdrag0n/0.0.1-alpha01/monet-kdrag0n-0.0.1-alpha01.module",
    "group": "me.heizi.monet-kdrag0n",
    "module": "monet-kdrag0n",
    "version": "0.0.1-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "monet-kdrag0n-jvm-0.0.1-alpha01.jar",
          "url": "monet-kdrag0n-jvm-0.0.1-alpha01.jar",
          "size": 54340,
          "sha512": "0c1f7b714281371e6e69fd3981462d502da3d41b4ff31b729a16f2ae9b0a8be818348f76c89f194cd895d8b767ec511011222f3c714bbc8e2c8438d3299b2dc0",
          "sha256": "67f6764414601814669e3ce04e0b112a1485cf0d26a524cd06e2002d38bc1968",
          "sha1": "cf26a644abd5215e2bbfb768ec3d8c8616564eaf",
          "md5": "aa631d435d36b0e06e69dcaec68da0a2"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "dev.kdrag0n",
          "module": "colorkt",
          "version": {
            "requires": "1.0.5"
          }
        },
        {
          "group": "io.github.aakira",
          "module": "napier",
          "version": {
            "requires": "2.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "monet-kdrag0n-jvm-0.0.1-alpha01.jar",
          "url": "monet-kdrag0n-jvm-0.0.1-alpha01.jar",
          "size": 54340,
          "sha512": "0c1f7b714281371e6e69fd3981462d502da3d41b4ff31b729a16f2ae9b0a8be818348f76c89f194cd895d8b767ec511011222f3c714bbc8e2c8438d3299b2dc0",
          "sha256": "67f6764414601814669e3ce04e0b112a1485cf0d26a524cd06e2002d38bc1968",
          "sha1": "cf26a644abd5215e2bbfb768ec3d8c8616564eaf",
          "md5": "aa631d435d36b0e06e69dcaec68da0a2"
        }
      ]
    }
  ]
}
