{
  "formatVersion": "1.1",
  "component": {
    "url": "../../khell-log/0.0.0-alpha01/khell-log-0.0.0-alpha01.module",
    "group": "me.heizi.kotlinx",
    "module": "khell-log",
    "version": "0.0.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "khell-log-jvm-0.0.0-alpha01.jar",
          "url": "khell-log-jvm-0.0.0-alpha01.jar",
          "size": 4966,
          "sha512": "a1e355f2aa95e1075f871ffdcadb89d7f4fccc0136965ee7d2b02a34ddc435f614c49568ae3891a7a46580d23a3ac808b6be2afa4fa30273c149a0a66255760f",
          "sha256": "7b4119cdc4f9520b34264e88cabefec7b7f9b3fc09dfe85e30388f22e654b088",
          "sha1": "b2de1c8e709cc0d0bfb6a90832736f8d378887a4",
          "md5": "cde380085b97670d68b83d6407a00f48"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "khell-log-jvm-0.0.0-alpha01.jar",
          "url": "khell-log-jvm-0.0.0-alpha01.jar",
          "size": 4966,
          "sha512": "a1e355f2aa95e1075f871ffdcadb89d7f4fccc0136965ee7d2b02a34ddc435f614c49568ae3891a7a46580d23a3ac808b6be2afa4fa30273c149a0a66255760f",
          "sha256": "7b4119cdc4f9520b34264e88cabefec7b7f9b3fc09dfe85e30388f22e654b088",
          "sha1": "b2de1c8e709cc0d0bfb6a90832736f8d378887a4",
          "md5": "cde380085b97670d68b83d6407a00f48"
        }
      ]
    }
  ]
}
