{
  "formatVersion": "1.1",
  "component": {
    "url": "../../khell/0.0.1-alpha03/khell-0.0.1-alpha03.module",
    "group": "me.heizi.kotlinx",
    "module": "khell",
    "version": "0.0.1-alpha03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        },
        {
          "group": "me.heizi.kotlinx",
          "module": "khell-log",
          "version": {
            "requires": "0.0.1-alpha03"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "khell-jvm-0.0.1-alpha03.jar",
          "url": "khell-jvm-0.0.1-alpha03.jar",
          "size": 89027,
          "sha512": "f79f8bb0d8667e5f73dae895e9ba95da841fef100736dbf335960f0e8ab3bec676ff15358ff641bfc2e49686f01d57df6260cb263a6aa9efc6f75e742159ef49",
          "sha256": "86ef6c000822142f59e0ad8c717d176356d8dca7fb6fa1569b1145ff99a89d17",
          "sha1": "4c0cd46d01fde7ea767074cbd8d018303e55a14e",
          "md5": "1d65dd05d6b51c2390dcd61c91a170e7"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        },
        {
          "group": "me.heizi.kotlinx",
          "module": "khell-log",
          "version": {
            "requires": "0.0.1-alpha03"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.20"
          }
        },
        {
          "group": "me.heizi.kotlinx",
          "module": "khell-api",
          "version": {
            "requires": "0.0.1-alpha03"
          }
        }
      ],
      "files": [
        {
          "name": "khell-jvm-0.0.1-alpha03.jar",
          "url": "khell-jvm-0.0.1-alpha03.jar",
          "size": 89027,
          "sha512": "f79f8bb0d8667e5f73dae895e9ba95da841fef100736dbf335960f0e8ab3bec676ff15358ff641bfc2e49686f01d57df6260cb263a6aa9efc6f75e742159ef49",
          "sha256": "86ef6c000822142f59e0ad8c717d176356d8dca7fb6fa1569b1145ff99a89d17",
          "sha1": "4c0cd46d01fde7ea767074cbd8d018303e55a14e",
          "md5": "1d65dd05d6b51c2390dcd61c91a170e7"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "khell-jvm-0.0.1-alpha03-sources.jar",
          "url": "khell-jvm-0.0.1-alpha03-sources.jar",
          "size": 6583,
          "sha512": "ebab3722f805d7f6c4b75f17fa01a4593708dc2a3dd1f31e0f32c1a660be22ba8f34fd7e071baa1f7d9fe0cd376c4a83cbf928311acd7664386c4ac4841386cc",
          "sha256": "39675839f3d78f23c2eea36112e825e1c7d2468945202317cefb7df07a41c25e",
          "sha1": "0553e1e9d9feeb48247b2e0b5f4dd3760ef1e884",
          "md5": "37a02ccb6eded86ebb3cefe1b872ffbc"
        }
      ]
    }
  ]
}
